* Data binary transfers

use stream/multibyte

* Architecture

The game accepted the input performed computations changing its state
and displayed that state in a monitor, speakers etc.

The inputs are located in separate computers across another network.


The client sends the input and the server tells what to display.

In the most ideal scenario lets assume we have infinite resources.

Lets imagine the latency is 0.

When we have this kind of network we can actually treat this system of
server + client as basically a single device.


You can think of a players 'controller' as just a client which is
connected over very fast network.


The client just takes all the input it receives from the user and it
sends all of the input to the server.


The server updates the state

And sends the entirety of the state of the game to the client

and client just displays that. And of course it does that for each
individual client.


We write separate programs that we run on separate parts of those
systems.

In case of a web application, you have frontend and backend.

essentially you connect to a server. Server sends you back a program that
the client is supposed to run. THat program connects back to the
server and now you have two programs communicating with each other.


This kind of situation even happens on a single machine. On a single
machine that also happens when you are doing graphics with CPU's.

shaders are prgorams that run on the gpu. It takes a shader, (a program)


It is basically a keyboard that runs a signal over a very slow wire
and also i can program that keyboard. I can send some code into that
keyboard and it do things for me.

Let all of the parts of the system have a copy of the state of the
game.

They are running this copy simultaneously and they are updating them
simultaneously.

if some client receives input, it sends that input to the server.o

For example.

The client communicates that a key is being held. (The key that moves
to the right).

The server takes a note. so this client is holding a key to the right.
notifies all the clients.  Everyone, that motherfucker is holding the
key that moves to the right.

Everyone is computing their own state.


There should be a mechanism that lets servers to say:

lets synchronize our state.

probably some discrepancies have accumulated.




* Sharing state - updating state
* Coding conventions
messages/outgoing
messages/incoming

function signatures:
client(incoming): (state, event)
client(outgoing): (state, event)
server(incoming): (state, event)
server(outgoing): (state, event)

Create a circular reference to globalThis named `g`.
Always access global variables using: `g.`

Event:
{
  type: "",
  msg: {},
  player: {},
  ...rest
}

* State synchronization and malicious intent prevention

Both the clients and the server operate under an infinite loop where on each
`TICK` the state is re-evaluated. This model effectively simulates a continuous
progression through linear time. This model runs independently on each client
and the server, presenting a challenge:

Can we guarantee an identical state across all clients and server, considering
the asynchronous and distributed nature of the operating context?


Consider the example:

1. Player 'A' clicks on the game map.
2. The client picks up the event, updates its state, and then transmits the event.
3. The server picks up the event, updates its state, and then transmits the event
   to all other players.
4. Player 'B' receives the event, updates Player's 'A' state.


These actions will run along the game infinite loop, which means that as soon as
(1) took place the client's game loop updated its state, moving the player
across the map.

When (4) took place, player (1) has already moved in his states map. At this
specific moment, the state between (1) and (3) and (4) have already diverged.


There might be multiple methods to deal with preventing a diverged state, I have
picked up the following:


1. Player 'A' clicks on the game map.
2. The client picks up the event, does NOT update its state, and then transmits
   an event that EXPRESSES an INTENT to move.
3. The server picks up the event, and transmits the ACTUAL MOVING event to all
   players including player 'A'. The contents of this event will contain NOT the
   state of the player 'A' as found in the client but rather the state of player
   'A' of the server.
4. All players pick up the event and update their state simultaneously.
