export const MessageType = Object.freeze({
  PLAYER_CONNECTED: "PLAYER_CONNECTED",
  PLAYER_DISCONNECTED: "PLAYER_DISCONNECTED",
  PLAYER_JOINED: "PLAYER_JOINED",
  PLAYER_MOVING: "PLAYER_MOVING",
  PLAYER_NAUGHTY: "PLAYER_NAUGHTY",
});
